# Generated by Django 3.2.11 on 2024-09-25 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('length_of_cycle', models.IntegerField()),
                ('length_of_menses', models.IntegerField(default=0)),
                ('length_of_luteal', models.IntegerField()),
                ('total_num_of_high_days', models.IntegerField()),
                ('total_num_of_peak_days', models.IntegerField()),
                ('total_days_of_fertility', models.IntegerField()),
                ('total_fertility_formula', models.IntegerField(default=0)),
                ('bmi', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
