# Generated by Django 3.2.11 on 2024-10-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='predicted_next_ovulation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prediction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
