# Generated by Django 3.2.11 on 2024-10-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241017_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='predicted_next_ovulation',
            new_name='predicted_next_ovulation_date',
        ),
    ]
